name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project true
      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: poetry-venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install/update package and dependencies
        run: poetry install
      - name: Test with Pytest and measure coverage
        run: poetry run pytest --cov-report=xml --cov=pecho tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
