name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      python-version: '3.9'
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project true
      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: poetry-venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Get package version
        id: package-version
        run: echo ::set-output name=version::$(poetry version | grep -Po "\d+\.\d+\.\d+$")
      - name: Check if tag matches package version
        if: steps.tag.outputs.tag != steps.package-version.outputs.version
        run: |
          echo Tag: ${{ steps.tag.outputs.tag }}
          echo Package version: ${{ steps.package-version.outputs.version }}
          echo Tag and package version do not match
          exit 1
      - name: Install/update package and dependencies
        run: poetry install
      - name: Create release ${{ steps.tag.outputs.tag }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: 'false'
          prerelease: 'false'
      - name: Build and publish to PyPi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
